### ISSUE TITLE
Add origin information to push notification dialog/screen

### ISSUE THREAD

**Issue by n370** [nearform/optic-expo#22]
As a user I'd like to know which service is requesting my approval to get an OTP code with a push notification.

**Comment by simoneb** [comment]
This can be implemented in at least a couple of different ways:

- accept additional information in the API request to generate a OTP
- associate information to a token (that randomly generated in the app for a secret) so that 1 token <-> 1 piece of contextual information that wouldn't need to be sent by the client making the request because it's associated to the token so it can be displayed by the app when the push notification is received

**Comment by tiagoheliob** [comment]
It was implemented on this PR https://github.com/nearform/optic-expo/pull/149 you can check the PR's description for more info
