### ISSUE TITLE
Update `README` with more details about how to obtain npm secret

### ISSUE THREAD

**Issue by radomird** [nearform/optic-expo#442]
When 2FA is already enabled on the `npm` profile before using the optic expo app it is not clear, from the docs, how to obtain the npm secret. This needs an update of the Readme file.

**Comment by simoneb** [comment]
This isn't strictly speaking something specific to this app. I'm not sure how we can document this because it greatly depends on which tool you're using to store your 2FA secrets. The tool stores the secret somewhere (a string which can be represented as a QR code) but whether and how they provide access to the underlying secret, as opposed to just 2FA passwords generated from it, greatly depends on the tool.
